name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake build-essential
        
    - name: Build GTest
      run: |
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        
    - name: Build project
      run: make
      
    - name: Run tests
      run: make run_test
      
    - name: Run program
      run: ./program.out <<< "0"
      
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
      token: ${{ secrets.CODECOV_TOKEN }}
